<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BovinSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('bovins')->insert([
            [
                'id_bov' => 4856,
                'race' => 'Meh Type Race etc....',
                'dateachat' => '2019-03-07',
                'prixachat' => 500.99,
                'poidachat' => 35.5,
                'lieuachat' => 'Marrakech bla bla',
                'datevente' => '2019-03-14',
                'prixavente' => 2500,
                'poidvente' => 75,
                'lieuvente' => 'sou9 blkjfeazblo',
                'vendu' => true,
                'mort' => false,
                'datemort' => null,
                'id_etab' => 3,
                'id_vend' => 2,
                'id_q' => 2,
                'poidAct' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_bov' => 74865,
                'race' => 'test',
                'dateachat' => '1999-11-10',
                'prixachat' => 250,
                'poidachat' => 30,
                'lieuachat' => 'kech',
                'datevente' => '2019-03-15',
                'prixavente' => 5000,
                'poidvente' => 75,
                'lieuvente' => 'kech',
                'vendu' => true,
                'mort' => false,
                'datemort' => null,
                'id_etab' => 3,
                'id_vend' => 2,
                'id_q' => 2,
                'poidAct' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_bov' => 485623,
                'race' => '3jel 1st Quality bla bla',
                'dateachat' => '2019-03-15',
                'prixachat' => 501,
                'poidachat' => 35,
                'lieuachat' => 'Marrakech 9le3t sraghna .',
                'datevente' => null,
                'prixavente' => null,
                'poidvente' => null,
                'lieuvente' => null,
                'vendu' => false,
                'mort' => false,
                'datemort' => null,
                'id_etab' => 3,
                'id_vend' => 3,
                'id_q' => 1,
                'poidAct' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_bov' => 1132456,
                'race' => '3jel',
                'dateachat' => '2011-11-11',
                'prixachat' => 500,
                'poidachat' => 25,
                'lieuachat' => 'Marrakech',
                'datevente' => '2019-03-15',
                'prixavente' => 2500,
                'poidvente' => 75,
                'lieuvente' => 'marrakech',
                'vendu' => false,
                'mort' => false,
                'datemort' => null,
                'id_etab' => 3,
                'id_vend' => 1,
                'id_q' => 2,
                'poidAct' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_bov' => 7846153,
                'race' => 'testing',
                'dateachat' => '1952-11-10',
                'prixachat' => 500,
                'poidachat' => 56,
                'lieuachat' => 'kech',
                'datevente' => '2019-05-15',
                'prixavente' => 0,
                'poidvente' => 0,
                'lieuvente' => '',
                'vendu' => false,
                'mort' => true,
                'datemort' => '2019-03-15',
                'id_etab' => 3,
                'id_vend' => 1,
                'id_q' => 2,
                'poidAct' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_bov' => 123456789,
                'race' => '3jel',
                'dateachat' => '2019-03-15',
                'prixachat' => 350.01,
                'poidachat' => 50.5,
                'lieuachat' => 'Marrakech - chi bled',
                'datevente' => null,
                'prixavente' => null,
                'poidvente' => null,
                'lieuvente' => null,
                'vendu' => false,
                'mort' => false,
                'datemort' => null,
                'id_etab' => 3,
                'id_vend' => 2,
                'id_q' => 2,
                'poidAct' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
